
project:
  type: website
  output-dir: docs

  resources: ["img/**", public/**]   

  preview: 
    browser: false
    port: 3000

execute:
  freeze: auto
  cache: true

metadata: 
 side-photo: "img/curva.png"



website:
  title: "Training Center SW"
  bread-crumbs: true

  sidebar:
    title: "Training Center SW"
    style: "docked"
    collapse-level: 1
    search: false
    alignment: center
    logo: public/logo-text.png
    contents:
      - index.qmd
      - section: pages/Bloque1/bloque1.qmd
        
        contents:
          - section: "Semana 0"
            contents: 
              - pages/Bloque1/entorno.qmd
          - section: "Semana 1"
            contents:
              - pages/Bloque1/html.qmd
              - pages/Bloque1/t1.qmd
              - pages/Bloque1/MAhtml2.qmd
              - pages/Bloque1/t1a.qmd
          - section: "Semana 2"

          - text: "Próximamente..."
      - section: "Bloque II Programación"
      - section: "Bloque III Interacción"
      - section: "Bloque IV Comunicación"

      - pages/rubric.qmd

    footer: "![](https://i.imgur.com/jbGUd7N.png)<br><br><br> ©Javier Ribal del Río <br> 2025 - Hyperloop UPV"
  repo-url: https://github.com/HyperloopUPV-H8/Web-TC-SW


format:
  html:
    theme:
      light: [flatly, style/theme.scss]
      dark: darkly
    toc: true
    lang: es
    code-copy: true
    code-overflow: wrap
    toc-depth: 4
    anchor-sections: true
    css: style/main.css
  pdf:
    documentclass: article
    toc: true
    number-sections: true
    geometry:
      - margin=2.5cm
    include-in-header: headfoot.tex
          